# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'BadgeIdKinvey' do
  pod 'React', '~> 0.11.0'
  pod 'KinveyKit'
end

# target 'BadgeIdKinveyTests' do
#
# end
#
